version: '3.8'

services:
  ### RabbitMQ #############################################
  rabbitmq:
    build: ./rabbitmq
    ports:
      - "{RABBITMQ_NODE_HOST_PORT}:5672"
      - "{RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
